### ISSUE TITLE
ServerInfo Name strips the first character

### ISSUE THREAD

**Issue by MagicTrevor** [cyilcode/SteamQueryNet#3]
It appears the first character of the `Name` property of `ServerInfo` is being stripped.

Expected: 
`name": "Atlas_A2 - (v18.76)",`

Actual:
`name": "tlas_A2 - (v18.76)",`

**Comment by cyilcode** [comment]
@MagicTrevor I am sorry about that. It looks like i have made a small miscalculation on response header count strip. I am publishing the required fixed asap.

**Comment by MagicTrevor** [comment]
Not a problem! It’s working well otherwise.
