### ISSUE TITLE
ServerInfo Players returns Max players when 0

### ISSUE THREAD

**Issue by Phobiia** [cyilcode/SteamQueryNet#5]
I have a 50 slot server and when no one is on serverInfo.Players is 50

**Comment by cyilcode** [comment]
Hey @Phobiia sorry for that. I will look into it as soon as possible.

**Comment by Phobiia** [comment]
No rush, I managed to get around it by using the PlayerList .count

Thanks!

**Comment by cyilcode** [comment]
@Phobiia Hey again. Library version v1.0.6 has been released. This issue must be fixed on the new version.

Also, i have updated a few more stuff as well. Please check out [CHANGELOG.md](https://github.com/cyilcode/SteamQueryNet/blob/master/CHANGELOG.md) to get informed what has changed and [README.md](https://github.com/cyilcode/SteamQueryNet/blob/master/README.md) reflect any hard-deprecation changes into your project.

Thanks for notifying.
